config/routes.rb
Theweekend::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :weekends,      only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :votes,         only: [:create, :destroy]
  root  'feeds#home'
  match '/signup',     to: 'users#new',               via: 'get'
  match '/signin',     to: 'sessions#new',            via: 'get'
  match '/signout',    to: 'sessions#destroy',        via: 'delete'
  match '/users',      to: 'users#index',             via: 'get'
  match '/search',     to: 'search#index',            via: 'get'

  

end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<div class="weekends">
  <%= render @weekends %>
</div>
<%= link_to 'Load More Weekends', root_path(:page => @weekends.next_page, week: @week.id),
  remote: true, class: "load-more-weekends" if @weekends.next_page %>

app/views/shared/_search.html.erb
<div class="searchbar">
  <%= form_tag(search_path, method: "get", style: "margin: 5px 0 0 0") do %>
    <%= text_field_tag(:q, nil, placeholder: "Search") %>
    <%= submit_tag("Search", class: "btn") %>
  <% end %>
</div>

app/views/shared/_signin.html.erb
<div class='login-page'>
  <div class='login'>
    <header>
      <h1>TheWeekend</h1>
    </header>
    <%= form_for(:session, url: sessions_path, :class => "form-horizontal", :role => "form") do |f| %>
    <p>
      <%= f.text_field :name_or_email, :placeholder => "Username or email" %>
    </p>
    <p>
      <%= f.password_field :password, :placeholder => "Password" %>
    </p>
      <%= f.submit "Sign in", class: "btn btn-default btn-primary" %>
    <% end %>
    <%= link_to "Sign up!", signup_path %>
  </div>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>" class="stat following">
      <div class="stat-num"><%= @user.followed_users.count %></div>
    Following
  </a>
  <a href="<%= followers_user_path(@user) %>" class="stat followers">
      <div class="stat-num"><%= @user.followers.count %></div>
    Followers
  </a>
  <div class="stat weekend-count">
    <div class="stat-num"><%= @user.weekends.count %></div>
    Weekends
  </div>
</div>

app/views/shared/_user_info.html.erb
<col-md-1>
  <%= link_to "view my profile", current_user %>
</span>
<span11>
  <%= pluralize(current_user.weekends.count, "weekend") %>
</span>

app/views/shared/_weekend_images.html.erb
<% weekend.images.each do  |image| %>
  <%= image_tag image.image.url.to_s, style: "width: 100%" %>
<% end %>