config/routes.rb
Theweekend::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :weekends,      only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :votes,         only: [:create, :destroy]
  root  'feeds#home'
  match '/signup',     to: 'users#new',               via: 'get'
  match '/signin',     to: 'sessions#new',            via: 'get'
  match '/signout',    to: 'sessions#destroy',        via: 'delete'
  match '/users',      to: 'users#index',             via: 'get'
  match '/search',     to: 'search#index',            via: 'get'

  

end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-inverse navbar-fixed-bottom">
      <%= link_to "Contact", 'mailto:raditude28@gmail.com', class: "navbar-text" %>
      <p class="navbar-text"> ©2013 The Weekend </p>
</footer>

app/views/layouts/_header.html.erb
<div id="header">
  <% if @week && @week.next %>
    <%= link_to '', root_path(:week => @week.next.id),
        class: "header-weekend-nav previous" %>
  <% end %>
  <% if @week && @week.previous %>
    <%= link_to '', root_path(:week => @week.previous.id),
        class: "header-weekend-nav next fa"%>
  <% end %>
  <div class="menu">
    <a class="logo">TheWeekend</a>
    <ul class="menu-list">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Users", users_path %></li>
      <li><%= link_to "My Profile", user_path(current_user) %></li>
      <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
    </ul>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </body>
</html>